secrets:
  common:
    - path: terraform/github/actions/terraform-provider-postgresql/common
      version: 0
    - path: common/github/actions/terraform-provider-postgresql/to_be_classified
      version: 1
